### ISSUE TITLE
Support for TiddlyWiki

### ISSUE THREAD

**Issue by ifethereal** [asamuzaK/withExEditor#132] opened 2020-06-01 09:53 UTC
First of all, thanks for this extension. This is exactly what I've been looking for. I'm using it right now with gVim to write this issue!

I had planned to use this with [TiddlyWiki][TW], using Google Chrome and gVim on Windows 10. Short version is that, within the textbox for editing tiddlers, the extension isn't able to work for me as for a normal text input.

Steps:
1.  Go to https://tiddlywiki.com .
2.  Click on the `+` button (_Create a new tiddler_) on the right side panel.
3.  Right click into the text area which has the placeholder text _Type the text for this tiddler_. Then select _withExEditor_ > _Edit Text with xxx_ from the context menu. The editor will execute.
4.  At this point, for me either the editor is filled with CSS code (probably TiddlyWiki CSS), or the editor is empty. In either case, whatever I save into the editor will not be reflected in the text area on TiddlyWiki once I save and quit the editor.

Thank you in advance for your help!

[TW]: https://tiddlywiki.com/
[1]: https://github.com/jlebon/textern/issues/56

**Comment by asamuzaK** [comment] 2020-06-01 10:45
Works for me

**Comment by ifethereal** [comment] 2020-06-01 11:47
Anything I can share/inspect to show why it's not working for me?

Sometimes the editor will be filled with the right text when started, but I still haven't seen it sync back to the TiddlyWiki text input after I save and close the editor.

Occasionally the editor will also not start at all, and the JavaScript console will have this error:
```
Uncaught (in promise) DOMException: Failed to execute 'querySelectorAll' on 'Document': '#abId0.23102560483467527 div' is not a valid selector.
    at createIdData (chrome-extension://koghhpkkcndhhclklnnnhcpkkplfkgoi/js/content.js:951:26)
    at createContentData (chrome-extension://koghhpkkcndhhclklnnnhcpkkplfkgoi/js/content.js:1261:21)
    at postContent (chrome-extension://koghhpkkcndhhclklnnnhcpkkplfkgoi/js/content.js:1353:24)
    at determineContentProcess (chrome-extension://koghhpkkcndhhclklnnnhcpkkplfkgoi/js/content.js:1413:10)
    at handlePortMsg (chrome-extension://koghhpkkcndhhclklnnnhcpkkplfkgoi/js/content.js:1806:21)
    at portOnMsg (chrome-extension://koghhpkkcndhhclklnnnhcpkkplfkgoi/js/content.js:1868:26)
```

[1]: example.com "Dummy link"

**Comment by asamuzaK** [comment] 2020-06-01 12:38
Ah, I was testing with Firefox.
Now, confirmed with Chrome.

I'd recommend using Firefox for a workaround.

**Comment by ifethereal** [comment] 2020-06-01 12:44
No worries. I'll use Firefox in the meantime.

I tried to dig around in Chrome as much as I could. It seemed like withExEditor was targeting the wrong element.

This is the one it targeted:
![](https://i.imgur.com/JBJOjDK.png)
but it was supposed to be this one:
![](https://i.imgur.com/T78aASk.png)

The correct target looks like it's in an `<iframe>`:
![](https://i.imgur.com/FsjkP3y.png)

**Comment by asamuzaK** [comment] 2020-06-01 13:01
I can't imagine why they are using iframe...

Is there a way to add an id on textarea by yourself?

**Comment by ifethereal** [comment] 2020-06-01 13:21
Unlikely to be possible from the TiddlyWiki user interface, and unfortunately I'm not familiar enough with JavaScript to do it from the backend.

**Comment by asamuzaK** [comment] 2020-06-01 13:27
https://stackoverflow.com/questions/8917593/do-chrome-extensions-access-iframes

looks like this?

**Comment by ifethereal** [comment] 2020-06-01 13:37
Would love to give you an answer but I think I'm outside my depth already. Let me know if you want me to test anything, however.

Having said that, if I'm looking at the right place, don't you [already have `all_frames` set to `true`][1]?

[1]: https://github.com/asamuzaK/withExEditor/blob/263d731ef6da45ab7cf186fd03b26aa4351c577c/src/manifest.json#L43

**Comment by asamuzaK** [comment] 2020-06-01 14:01
yes
https://github.com/asamuzaK/withExEditor/blob/master/src/manifest.json#L43

I suppose tiddlywiki is creating iframe dynamically.

**Comment by asamuzaK** [comment] 2020-06-01 14:07
It's a restriction in Chrome so that I think there is nothing I can do to fix this.

There is a MutationObserver API which checks DOM change, but it's not reallistic to add that in every page.

**Comment by asamuzaK** [comment] 2020-06-02 15:37
I'll do some more research before I conclude this WONTFIX.

**Comment by asamuzaK** [comment] 2020-06-17 06:04
Mostly fixed, but still have caveat.
Reopened.

**Comment by asamuzaK** [comment] 2020-06-17 06:12
Caveat:
On Blink, "browser.windows.onFocusChanged" event doesn't fire when focus is moved from editor to browser for some reason.

**Comment by asamuzaK** [comment] 2020-06-17 07:05
Ref [387377 - chrome.windows.onFocusChanged.addListener bugged - chromium](https://bugs.chromium.org/p/chromium/issues/detail?can=2&q=chrome.windows.onFocusChanged.addListener&colspec=ID%20Pri%20M%20Iteration%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified&id=387377&thanks=387377&ts=1403370788)

It's a issue of Blink itself.
For this one, there is really nothing I can do.

**Closed as completed by asamuzaK** 2020-06-17 07:05 UTC

**Comment by asamuzaK** [comment] 2020-06-17 07:16
Chrome Web Store does not provide a way for try builds, so please wait for the next release.
It will be released at the end of this month.

**Comment by asamuzaK** [comment] 2020-07-04 07:29
New version released a couple days ago.
Please check if it's working?

Thanks

**Comment by ifethereal** [comment] 2020-07-04 10:19
I've tested the new version (7.0.2) in Chrome.

As far as I can see, it works as you noted:

1. Starting the text editor via the plugin will open up a file containing the text that the browser's textbox has.
2. However, any write to the file from the text editor won't be reflected in the browser's textbox just by returning focus to the browser.
3. The textbox updates correctly once it is triggered to do so. Clicking around the page area on the original tab seems to trigger this. Changing tabs away and back to the original tab also triggers this.

Thanks for your work! You've already noted the caveat, so I think there's nothing left for this issue.
