### ISSUE TITLE
Can't edit text at crbug.com

### ISSUE THREAD

**Issue by rtoy** [asamuzaK/withExEditor#111] opened 2019-03-29 15:58 UTC
Visit https://crbug.com/new

In the "Description" box, right click to bring up the menu.  "Edit text" is greyed out for me, so I can't use this to edit the text.

If I put the mouse in that box and then press the my defined key sequence to edit, I get 4 editor windows.  They seem to be from various different tabs, but none of them have the text from the description box from crbug.com.

I'm not 100% sure, but I think this used to work.  Could be a change in crbug.com or maybe some change here.

**Comment by asamuzaK** [comment] 2019-03-29 16:12
Works for me.

Did you updated host recently, but not restarted withExEditor?
If so, maybe old Node process is still running.
Please restart withExEditor and try again.

* Click withExEditor toolbar button.
* Click "Reload" button.

**Comment by rtoy** [comment] 2019-03-29 17:20
Ah, it works just great with Firefox.  But doesn't work with Chrome (beta at least).

I did update the host recently because withExEditor said it wasn't compatible anymore.  Reloading helps because the menu item isn't greyed out anymore.  But it doesn't work.  It loads up all kinds of random text (including html source) in several windows.

**Comment by asamuzaK** [comment] 2019-03-29 17:34
Tested with Chrome Canary and Vivaldi, but can't confirm. 

I'm not sure but maybe restarting withExEditor is not enough on Blink browsers?
What happens if you close and restart the browser?

**Comment by asamuzaK** [comment] 2019-03-29 17:55
Another possibility is that Blink browsers assign processes to each tab, so even after reloading withExEditor, you may also need to reload the corresponding page (tab).
It's just a possible scenario, I have not  verified.

**Comment by rtoy** [comment] 2019-03-29 18:30
Hmm.  I updated the host to 5.0.6.  Restarted chrome (beta) and visited crbug.com/new.  Now the menu item is greyed out again.  Other sites like github work fine; the menu item works and so does the hot key.  Just not crbug.com for me.

**Comment by asamuzaK** [comment] 2019-04-01 17:07
I found and fixed a bug when restarting the extension, but there is still a difference between Gecko and Blink.
It seems that Blink won't reestablish a connection between background script and content scripts, unless the tab is explicitly reloaded.
I'm not sure if that is the browser's expected default behavior or it's due to the [polyfill](https://github.com/mozilla/webextension-polyfill).

**Comment by rtoy** [comment] 2019-04-02 18:17
Updated withExEditor to 6.0.1 and the host to 5.0.10.  Now the menu item to edit is greyed out.  But it works great here on github since I used withEXEditor to edit this message.

Something weird about crbug.com or my setup.

**Comment by asamuzaK** [comment] 2019-04-02 22:50
Have you tried force reload (Ctrl + F5), and/or clear cookie?

**Comment by rtoy** [comment] 2019-04-03 16:27
Yep, tried that just now.  Still nothing works. I even went and disabled all extensions that I could.  It's still greyed out.

Don't know what else to do except maybe use Firefox if I really want to edit a bug using withExEditor.

**Comment by asamuzaK** [comment] 2019-04-03 23:29
Have you tried switching to another Google account?
That's all I can think of as a possible remaining.

**Comment by rtoy** [comment] 2019-04-15 19:15
I tried again on a different machine (and account) and everything works.

I looked again on my current system and noticed I have 3 profiles (unlike my other machine that has just one). One of them does not have the editor extension installed. However, installing it doesn't seem to help.

So I'm guessing somehow the multi-profile in chrome changes how things work.

**Comment by asamuzaK** [comment] 2019-04-15 19:41
Do you mean profile = Google account? or profile = user profile of OS?

**Comment by rtoy** [comment] 2019-04-15 20:23
Google account.  Click on the icon next to the three dots to get to your account info and where you can also add more accounts.

I've had three profiles/accounts for probably close to five years now.  But as I mentioned before, this is something having to do with crbug.com as well, because I have no trouble with github because I used withExEditor to enter this message.  Works great there!

**Comment by asamuzaK** [comment] 2019-04-15 21:04
I can not reproduce even if I switch accounts.
Is it okay for you if I close this issue as invalid for now?

**Comment by rtoy** [comment] 2019-04-15 21:35
Up to you.

I did try with Chromium and have 3 separate accounts.  This all seems to work.  So something special about my current Chrome version (which is managed by my employer).  My chromium build is not managed by my employer.

**Comment by asamuzaK** [comment] 2019-04-15 21:40
Feel free to reopen when you find something.

**Closed as completed by asamuzaK** 2019-04-15 21:40 UTC
