### ISSUE TITLE
execute shortcuts not working (Firefox 60.0, Linux)

### ISSUE THREAD

**Issue by jcbradfield** [asamuzaK/withExEditor#81] opened 2018-05-18 19:39 UTC
Following the most recent update in my distribution (Xubuntu 16.04) to Firefox, the execute shortcuts (ctr+shift+e in my case) no longer do anything. Executing from context menu still works.

**Comment by asamuzaK** [comment] 2018-05-18 22:01
1. Open options page
2. Press `Ctrl + Shift + E` on input of `Execute The Editor Directly`

What happens?

BTW, `Ctrl + Shift + E` will open network console on Win10

**Comment by asamuzaK** [comment] 2018-05-19 01:58
Keyboard shortcuts in v5 uses the WebExtensions API.
With this change, if `Ctrl + Shift + E` is already assigned to another function, the shortcut will not work.
In that case, please consider another key combination.
Please refer to [commands - Mozilla | MDN](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/commands#Shortcut_values) for the key combinations that can be specified.

**Comment by jcbradfield** [comment] 2018-05-19 06:58
I see. It's quite hard to find combinations not in use! Ctrl+Shift+E works nowhere, because firefox uses it as a shortcut to the network page. Ctrl+Shift+U works on a web page, but not in a text input area, presumably because gtk or something is using it. But Ctrl+Shift+Q seems to be free.
Thank you for the explanation (and, of course, for the plugin!).

**Comment by asamuzaK** [comment] 2018-05-19 07:15
How about `Ctrl + Function Key (for example F1)`?

**Comment by jcbradfield** [comment] 2018-05-19 09:13
That's a bit of stretch on this laptop, because the "function keys" are media etc. keys by default, so ctrl+f1 actually means pressing ctrl+fn+f1. ctrl+shift+Q seems ok for me (I have ctrl and capslock swapped, of course:)

**Comment by asamuzaK** [comment] 2018-05-19 09:48
So, it's working again?
Can I close this?

**Comment by jcbradfield** [comment] 2018-05-19 16:59
Yes, do. But it might be good to put a warning somewhere - when something suddenly stops working for no apparent reason, not everybody is going to come here! In particular, your default of Ctrl+Shift+U seems no longer to work in text boxes.

**Comment by asamuzaK** [comment] 2018-05-20 00:19
There is a release note [withExEditor :: Versions :: Add-ons for Firefox](https://addons.mozilla.org/en-US/firefox/addon/withexeditor/versions/?page=1#version-5.0.0 "withExEditor :: Versions :: Add-ons for Firefox")
However, the problem is that most people will not look through this, since release note is not displayed when add-on is updated automatically...

**Closed as completed by asamuzaK** 2018-05-20 00:19 UTC

**Comment by asamuzaK** [comment] 2018-05-20 00:45
FYI, filed meta bug for keyboard shortcuts.  #82
